from app.models.role import Role
from app.models.user import User
from app.models.entity import Entity
from app.models.region import Region
from app.models.city import City
from app.models.postal_code import PostalCode
from app.models.location import Location
from app.models.device import Device
from app.models.area_code import AreaCode
from app.models.rak_number_block import RakNumberBlock
from app.models.number_range import NumberRange
from app.models.subscriber import Subscriber
from app.models.phone_number import PhoneNumber